### ISSUE TITLE
`enableTypeChecking: false` no longer works

### ISSUE THREAD

**Issue by novascreen** [gsoft-inc/craco#117]
When starting CRA with `typescript: { enableTypeChecking: false }` it gets stuck at
```
Files successfully emitted, waiting for typecheck results...
```

https://github.com/facebook/create-react-app/blob/71946b1ebab445d7e4f9efca39bf0fe0d4be30f3/packages/react-dev-utils/WebpackDevServerUtils.js#L187

it seems to wait for an event from the fork-ts-checker-webpack-plugin

looks related: https://github.com/facebook/create-react-app/issues/5784

**Comment by patricklafrance** [comment]
Hi @novascreen 

Thank you for reporting the issue.

I will try to have a look at this before the end of the week.

**Comment by patricklafrance** [comment]
I made a fix.

This is quite nasty, I had to override the call to the Webpack compiler to force the `useTypeScript` function argument to false.

For now, it's fine since all the code related to TS in this function is to display TS type checking error which is what the option disable.

Might have to revisit this later if they add new functionalities for TS through the Webpack compiler.

I don't use TS myself, I only test the fix on a brand new CRA app.

Could you test it please? Available as an alpha version:

https://www.npmjs.com/package/@craco/craco/v/5.6.0

Thank you,

Patrick

**Comment by novascreen** [comment]
I'll try to find some time on the weekend. Thank you for addressing this so
quickly!

**Comment by novascreen** [comment]
@patricklafrance I gave it a try this morning, seems to work. Thank you!

**Comment by socketpair** [comment]
Hey, guys. Is the bug fixed ? @patricklafrance @novascreen
