### ISSUE TITLE
Can I merge Craco configs?

### ISSUE THREAD

**Issue by adi518** [gsoft-inc/craco#146]
Is there an API for merging entire Craco configs together? I'm creating a CLI tool for generating an internal CLI tool, so eventually there would be three configs I want to merge together.

**Comment by patricklafrance** [comment]
Hi @adi518,

No there is nothing like this at the moment.

Patrick

**Comment by adi518** [comment]
I see. I'll try to come up with a solution.

**Comment by adi518** [comment]
How hard would it be to support an array of functions instead of a single function? For example:
```js
module.exports = {
  babel: {
    loaderOptions: [
      (babelLoaderOptions, { env, paths }) => {
        return babelLoaderOptions
      },
      (babelLoaderOptions, { env, paths }) => {
        return babelLoaderOptions
      }
    ]
  }
}
```
It doesn't seem to make sense, but imagine every function is read from a different Craco configuration source. I want to be able to merge the result of each function, while keeping the merge responsibility within Craco of course.

**Comment by patricklafrance** [comment]
Hi @adi518,

I understand how it might be useful for your very specific use case but I don't think this is something that would improve CRACO since it already give enough flexibility by accepting an object literal or a function.

Have a look at the following code: https://github.com/gsoft-inc/craco/blob/master/packages/craco/lib/features/webpack/style/css.js#L29

This is done with lodash mergeWith: https://lodash.com/docs/4.17.15#mergeWith

**Comment by adi518** [comment]
Having looked at the API again, maybe I can merge them via plugins? like so:
```js
const cracoConfig = {
  plugins: [
    { plugin: { overrideCracoConfig: () => cracoConfig1 } },
    { plugin: { overrideCracoConfig: () => cracoConfig2 } },
    { plugin: { overrideCracoConfig: () => cracoConfig3 } }
  ]
}
```

**Comment by patricklafrance** [comment]
I doubt this is what you want, have you try it? I don't think there is anything in CRACO that will merge the configs for you.  My advice here is to write the merge code in your CLI.

The error happens because you returned an invalid CRACO config. In this case `reactScriptsVersion` is missing.

After CRACO load the user config, CRACO will merge the user config with the DEFAULTS which contains a default value for `reactScriptsVersion`. The defaults are applied before calling the plugins.

**Comment by patricklafrance** [comment]
I had a quick look at your project and my first though is if your concerns are distribution and avoiding redundant boilerplate code, you should instead provide a custom CRA template already configured with CRACO and a default `craco.config` file already setup with all the customizations that you need?

**Comment by adi518** [comment]
Sweet, I'll have a look at that, missed it somehow. The main purpose of the CLI is to bootstrap a custom CLI (`npx react-ryo-cli init` would create a CLI boilerplate). I also added a script for updating package.json, so you can easily replace the CRA scripts with your Craco based CLI scripts. That lead me into another idea for replacing CRA init and it seems custom templates would fit well in doing that, I initial thought of just calling the CRA init script and then customizing it, but looks like I can take a shortcut using custom templates, we'll see. :)

**Comment by patricklafrance** [comment]
I agree, that's why I am not much inclined into adding a merge api to CRACO. It sounds like a lot of maintenance.

**Comment by adi518** [comment]
So, for now I decided to go for the following approach. I will initiate Craco with my package own `craco.config.js`, then load the consumer config file, attach my plugin to it and return that. Sounds right?

As for merging, merging an app config file is quite an edge case and counters the goal of the cli purpose anyway, so I'll drop it.
