### ISSUE TITLE
adding stylus loader

### ISSUE THREAD

**Issue by bazo** [gsoft-inc/craco#147]
Hi, 

how can i add stylus loader https://github.com/shama/stylus-loader ?

i'm interested mainly in this part
```js
module: {
  loaders: [
    { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' }
  ]
}
```

thanks

**Comment by patricklafrance** [comment]
Hi @bazo,

I am not familiar with stylus so I don't know the exact recipe.

Usually when you want to add/update/delete a loader you should use [webpack.configure](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#configuration-overview) in the function format:

```
module.exports = {
    webpack: {
        configure: (webpackConfig, { env, paths }) => { return webpackConfig; }
    }
};
```

Or write a [custom plugin for CRACO](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#develop-a-plugin) which is what I recommended since you could then share it with others.

Whichever option you choose, you should also have a look at [CRACO utility functions](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#utility-functions).

Hope it helps,

Patrick
