### ISSUE TITLE
Babel plugins not applying to Jest

### ISSUE THREAD

**Issue by dustinlacewell** [gsoft-inc/craco#183]
I have
```js
    babel: {
        plugins: [
            ['@babel/plugin-transform-typescript', {
                allowNamespaces: true,
            }],
        ]
    },
```
in my `craco.config.js` and this allows me to properly build my project. However, when I run `npm run test` I get the following error:
```
 FAIL  src/music/IntervalQuality/index.test.ts
  ● Test suite failed to run

    SyntaxError: /home/ldlework/src/shapes-ui/src/music/IntervalQuality/index.ts: Namespace not marked type-only declare. Non-declarative namespaces are only supported experimentally in Babel. To enable and review caveats see: https://babeljs.io/docs/en/babel-plugin-transform-typescript

      78 | }
      79 | 
    >80 | export namespace IntervalQuality {
           |                  ^^^^^^^^^^^^^^^
      81 |     export function fromString(name: string): NullableIQ {
      82 |         return qualityFromAbbr[name] || qualityFromName[name.toLowerCase()];
      83 |     }
```
What do I need to do so that the Babel plugin is used in the context of testing?

**Comment by nmorozov** [comment]
@dustinlacewell Hi. I faced the same problem. I use linaria and CracoLinariaPlugin (it includes babel preset) and it works for project build, but not for tests. How did you resolve this problem?

**Comment by AntonioRedondo** [comment]
I have the same issue. CRACO config added to use webpack aliases works fine with `craco start`. But on tests running `craco test` I cannot use aliases since I get the error `Cannot find module '@alias/file' from 'src/Component.tsx'`.

I tried to create a repo to reproduce the error. But CRACO 6.4.3 isn't compatible with CRA 5.0.0. and if I try to use CRA 4.0.3, the CRA installation stops because it says I'm using an old version of CRA. 🤪

I'll try to reproduce the bug once CRACO is compatible with CRA 5.0.0.

**Comment by AntonioRedondo** [comment]
For those who are having issues with aliases on Jest with CRACO, they can work with the below addition on `package.json`:

```json
package.json:

{
  "name": "my-project",
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "craco eject"
  },
  "jest": {
    "moduleNameMapper": {
      "@/(.+)": "<rootDir>/src/$1"
    }
  }
}
```

Then normally running the tests with `npm t`.
