### ISSUE TITLE
How to add style loader nonce attribute

### ISSUE THREAD

**Issue by a-guerrero** [gsoft-inc/craco#222]
Hi, I'm trying to add the [style loader nonce attribute ](https://webpack.js.org/loaders/style-loader/#nonce) example like this:
```js
// craco.config.js
module.exports = {
  webpack: {
    module: {
      rules: [
        {
          test: /\.css$/i,
          use: [
            {
              loader: "style-loader",
              options: {
                attributes: {
                  nonce: "12345678",
                },
              },
            },
            "css-loader",
          ],
        },
      ],
    },
  },
};
```
but that's not working. Is there a way to make this work? I also played around with the craco `style` property but to be honest I didn't know how to fit this in there.

**Comment by patricklafrance** [comment]
Try with

```
{
    webpack: {
        configure: {
           ....
        }
    }
}
```

**Comment by patricklafrance** [comment]
Should also work with

```
style: {
        css: {
            loaderOptions: {
                attributes: {
                  nonce: "12345678",
                }
            }
        }
}
```

**Comment by a-guerrero** [comment]
Nope 😕,  with `webpack.configure` nothing happens, I don't get the `nonce` attribute in the style elements. And with `styles.css` I get this error:
```
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'attributes'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
```

**Comment by patricklafrance** [comment]
Oh right you want to add it the `style-loader` not the `css-loader`.

You can output the resulting webpack config with [CRACO API](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#api) and see if your nonce is added.

Internally CRACO use [webpack-merge](webpack-merge) to support `webpack.configure` so I guess it might to be something that is not supported by the package.

You can still do it manually by using the functional version of `webpack.configure` instead of an object literal.

**Comment by gsi-chao** [comment]
Any progress with this issue?
