### ISSUE TITLE
Is postcss.config.js ignored by craco?

### ISSUE THREAD

**Issue by StarpTech** [gsoft-inc/craco#263]
Hi, it looks like that `postcss.config.js` isn't loaded when running `craco build`. Is it supported?

**Comment by patricklafrance** [comment]
It's supported if you specify in your `craco.config.js` file:

```
{
    style: {
        postcss: {
            mode: "file"
        }
    }
}
```

https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#configuration-file

**Comment by StarpTech** [comment]
Great, thank you!

**Comment by StarpTech** [comment]
Unfortunately, this doesn't work I got the error:

```
Error: No PostCSS Config found in: /home/starptech/Repositories/starptech/test-project/packages/package-x/build
```

I have a `postcss.config.js` in the same directory where I start craco.

**Comment by toxsick** [comment]
@StarpTech are you working in a monorepo / with workspaces? If yes, try putting the `postcss.config.js` in the root of the monorepo. This works for me in combination with `mode: POSTCSS_MODES.file`.

But I would be interested how to make this work when the config is located inside the monorepo package folder, because I have a situation where the global config interferes with the configuration of another workspace package I have (that uses docusaurus)

regards

**Comment by StarpTech** [comment]
Thanks for the tip! Nevertheless, it's still a bug because it should work on the package level. A package is not aware of the workspace.
