### ISSUE TITLE
high vulnerabilities in dependencies

### ISSUE THREAD

**Issue by jakubkarabula** [gsoft-inc/craco#296]
Hello, I have noticed in my project that npm started to report high & moderate vulnerabilities in dependencies and it fails to resolve them with `npm audit fix`. I have found that it comes to @craco/craco package (newest version 6.1.2). I am using MacBook with macOs 10.15.7. I have tested the issue with a clean project (no other dependencies) and it reports the same (see screenshot below). It looks quite concerning to me, but perhaps it's my mistake somewhere (if so then sorry for bothering, I have however seen it in CI and on other machines with Ubuntu). I would really appreciate it if the vulnerabilities would be addressed by your team (I can also take a look at it and create a PR to your repo). Have a good day :)

![Screenshot 2021-05-27 at 12 21 17](https://user-images.githubusercontent.com/4799048/119811197-1bea6100-bee7-11eb-90c6-756ff0f4ae73.png)

**Comment by patricklafrance** [comment]
Hi @jakubkarabula 

I bootstrapped a new project with create react app WITHOUT craco and I still get these warnings so I believe the problem is with react-scripts dependencies and not craco.

![image](https://user-images.githubusercontent.com/794579/119837222-614f6400-bed0-11eb-8717-11f59020eaae.png)

Than you,

Patrick

**Comment by jakubkarabula** [comment]
Thanks, I haven't considered this. It looks that there is an [issue for this on CRA](https://github.com/facebook/create-react-app/issues/11012). Feel free to close the issue then.
