### ISSUE TITLE
babel-jest should be a peer dependency

### ISSUE THREAD

**Issue by chrisdchow** [gsoft-inc/craco#303]
Hi, I noticed that `create-jest-babel-transform` requires `babel-jest`, however that isn't reflected in the package.json (as a peerDependency?) or installation setup. Having a `craco.config` with babel plugins will caused `jest` to fail because of the missing dependency. My application doesn't use babel-jest directly, which is how I ran into this situation. It's an easy enough mitigation, however wanted to communicate this.

I observed this in v5.6.4 https://github.com/gsoft-inc/craco/blob/v5.6.4/packages/craco/lib/features/test/merge-jest-config.js and I think it still appears to be the case on master as well. https://github.com/gsoft-inc/craco/blob/master/packages/craco/lib/features/jest/create-jest-babel-transform.js

Thanks.

**Comment by patricklafrance** [comment]
Hi,

Thanks for the issue. CRACO could indeed have a peer-dependency on `babel-jest`. However since CRACO is dependent on `react-script` and it's already a dependency of `react-script`, I didn't feel the need to add it. In fact, if we choose to go this path, there would be a lot of dependencies to add.

I am not aware of the specifics of your setup but you should have somewhere in you dependencies tree a version of `babel-jest` since you installed `react-scripts`. The `jest` failure is odd.

Thank you,

Patrick
