### ISSUE TITLE
Adding CopyWebpackPlugin to craco.config.js

### ISSUE THREAD

**Issue by terrancecorley** [gsoft-inc/craco#326]
Can someone show me how to properly add CopyWebpackPlugin to a craco.config.js file? I can't seem to get the syntax right.

This is the example webpack gives for using this plugin...
```
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
  plugins: [
    new CopyPlugin({
      patterns: [
        { from: "source", to: "dest" },
        { from: "other", to: "public" },
      ],
    }),
  ],
};
```

**Comment by RT-TL** [comment]
What error do you get @terrancecorley?

**Comment by vanslly** [comment]
You are trying to use a Webpack plugin as a craco plugin.

Instead do the following:
```JavaScript
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
  webpack: {
    plugins: {
      add: [
        new CopyPlugin({
          patterns: [{ from: "serve.json", to: "" }],
        }),
      ],
    },
  },
};
```

Taking care to use a compatible version of `copy-webpack-plugin` of course. I'm using CRA which is compatible with webpack 4, so to install:
```
yarn add -D copy-webpack-plugin@6
```

Of course, this is a more advance case which is usually not required with CRA since you just drop files into `/public` and the CRA webpack config will copy all the files over to the `build` directory anyhow; but this illustrates how you could do it.

**Comment by terrancecorley** [comment]
Apologies for the delay here-- @vanslly thank you! I'll give that a go and give a status update here afterwards.
