### ISSUE TITLE
Attempted import error: 'PACKAGE' does not contain a default export (imported as 'PACKAGE').

### ISSUE THREAD

**Issue by Arcanorum** [gsoft-inc/craco#392]
I'm getting the following weird build error with only some specific packages.

```
johnathan@johnathan-hp-laptop:~/import-bug$ npm run build -w clients/game

> game@1.0.0 build
> craco build

Creating an optimized production build...
Failed to compile.

./src/index.tsx
Attempted import error: 'phaser' does not contain a default export (imported as 'Phaser').


npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: game@1.0.0 
npm ERR!   at location: /home/johnathan/import-bug/clients/game 
```

For example:
```
import Phaser from 'phaser'; <-- errors for this package, but this is how I always import it in other projects without error
import Leaflet from 'leaflet'; <-- but not this one

console.log(Phaser);
console.log(Leaflet);
```

With this minimal repro: https://github.com/Arcanorum/import-bug

- `npm i`
then build the app client
- `npm run build -w clients/game`

Relevant app file where error occurs: https://github.com/Arcanorum/import-bug/blob/master/clients/game/src/index.tsx

For context:
- Project is a monorepo using NPM workspaces, with a bunch of client apps, hence `/clients`.
- All dependencies are installed in the project root.
- Phaser comes with it's own type defs. Leaflet type defs are from `@types`.
- Have checked that the "phaser" package **does** export a default export (the `Phaser` namespace).

Dunno if this is a bug with CRACO, CRA, incompatibility with a monorepo setup like this, or me misunderstanding something, but the error is not very descriptive as to what build step specifically is failing.

**Comment by 1018715564** [comment]
I also got this error

**Comment by jacobwahoo** [comment]
I'm getting this error, too. It seems to be webpack related, but I haven't been able to find a fix for it yet. I am working on uplifting my project to react-scripts 5, which includes a bump up to webpack 5. We were using react-app-rewired, and started getting this error. I switched to craco, but the problem persisted.
In my case, the dependency is a Lerna subpackage (using yarn workspaces) that definitely has a default export.
(I've anonymized the project info a bit, because it's a private project)
```
PS C:\Git\SYSTM> yarn build
yarn run v1.22.18
$ yarn build-lerna && cross-env DISABLE_NEW_JSX_TRANSFORM=true craco build
$ npx lerna run build
lerna notice cli v4.0.0
lerna info versioning independent
lerna success - @mynamespace/api-client
Creating an optimized production build...
Failed to compile.

Attempted import error: '@mynamespace/api-client' does not contain a default export (imported as 'Client').


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The subpackage is symlinked in my node_modules as you'd expect. It has the following in the the package.json
```
{
  "name": "@mynamespace/api-client",
  "version": "3.0.0",
  "description": "",
  "private": true,
  "main": "dist/index.js",
  "typings": "dist/index.d.ts",
  ...
}
```

And in dist/index.js:
```
"use strict";
exports.__esModule = true;
var client_1 = require("./src/client");
exports["default"] = client_1["default"];
//# sourceMappingURL=index.js.map
```

It's probably also worth mentioning that if I just run tsc, the Lerna subpackage gets resolved just fine, which is why I think this is a webpack issue.
